flags: {}
extra-package-dbs: []
packages:
  - './owa-core'
extra-deps:
- HUnit-1.3.1.1
- QuickCheck-2.8.2
- ansi-terminal-0.6.2.3
- async-2.1.0
- call-stack-0.1.0
- directory-1.2.7.0
- extensible-exceptions-0.1.1.4
- hspec-2.3.2
- hspec-core-2.3.2
- hspec-discover-2.3.2
- hspec-expectations-0.8.2
- mtl-2.2.1
- parallel-3.2.1.0
- parsec-3.1.11
- primitive-0.6.1.0
- process-1.4.2.0
- quickcheck-io-0.1.2
- random-1.1
- setenv-0.1.1.3
- split-0.2.3.1
- stm-2.4.4.1
- text-1.2.2.1
- tf-random-0.5
- wl-pprint-1.2
- template-0.2.0.10
resolver: ghc-7.10
