resolver: ghc-7.10

packages:
- '.'

extra-deps: [directory-1.2.6.3
  , wl-pprint-1.2
  , mtl-2.2.1
  , parsec-3.1.11
  , split-0.2.3.1
  , text-1.2.2.1
  , HUnit-1.3.1.1
  , QuickCheck-2.8.2
  , async-2.1.0
  , random-1.1
  , tf-random-0.5
  , primitive-0.6.1.0
  , stm-2.4.4.1
  , hspec-2.2.3
  , process-1.4.2.0
  , hspec-core-2.2.3
  , hspec-discover-2.2.3
  , hspec-expectations-0.7.2
  , ansi-terminal-0.6.2.3
  , quickcheck-io-0.1.2
  , setenv-0.1.1.3]

flags: {}

extra-package-dbs: []

