name:
  owa-objc

version:
  0.1.0.0

ghc-options: -Wall

dependencies:
  - base
  - containers
  - owa-model
  - owa-utils
  - split
  - wl-pprint

library:
  source-dirs:
    src/
  other-modules:
    Objc.Utils
