name:
  owa-swift

version:
  0.3.0.0

ghc-options: -Wall

dependencies:
  - base
  - containers
  - owa-model
  - owa-utils
  - split
  - wl-pprint

library:
  source-dirs:
    src/

tests:
  swift-tests:
    main: Swift/Tests.hs
    source-dirs:
      - test/
    dependencies:
      - directory
      - hspec
      - owa-swift
      - process
