name:
  owa-parse

version:
  0.1.0.0

dependencies:
  - base
  - owa-model

library:
  source-dirs:
    src/
  other-modules:
    Parse.Utils
  dependencies:
    - containers
    - mtl
    - parsec
    - split
    - text

tests:
  parse-tests:
    main: Parse/Tests.hs
    source-dirs:
      - test/
    dependencies:
      - directory
      - hspec
      - owa-parse
