name:
  owa-parse

version:
  0.4.0.1

dependencies:
  - base
  - owa-model
  - parsec

library:
  source-dirs:
    src/
  other-modules:
    Parse.Utils
  dependencies:
    - containers
    - mtl
    - split
    - text

tests:
  parse-tests:
    main: Parse/Tests.hs
    source-dirs:
      - test/
    dependencies:
      - containers
      - directory
      - hspec
      - owa-parse
